In [1]:
import numpy as np

In [2]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
# 4행3열로 출력
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [4]:
# 1~10까지를 8등분 한 것
a = np.linspace(1, 10, 8)
print(a)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [5]:
a=np.array(['1.55','0.23','5.21','5'])
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.dtype)

<U4


In [7]:
a=a.astype(float)
print(a.dtype)

float64


In [8]:
a=np.array([1,2,3,4,5,6])

In [10]:
# a 배열에서 3보다 큰 값
print(a[a>3])

[4 5 6]


In [11]:
# a 배열에서 짝수 값
print(a[a%2==0])

[2 4 6]


In [12]:
# 배열의 슬라이싱
print(a[1:4])

[2 3 4]


In [13]:
a=np.arange(10, 100, 10).reshape(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [14]:
print(a[1:3, 1:3])

[[50 60]
 [80 90]]


In [15]:
print(a[:3, 1:])

[[20 30]
 [50 60]
 [80 90]]
