In [1]:
matrix_a=[[3,6],[4,5]]
matrix_b=[[5,8],[6,7]]

In [2]:
result=[[sum(row) for row in zip(*t)] for t in zip(matrix_a, matrix_b)]
print(result)

[[8, 14], [10, 12]]


In [5]:
import numpy as np
nmatrix_a=np.array([[3,6],[4,5]])
nmatrix_b=np.array([[5,8],[6,7]])
result=nmatrix_a+nmatrix_b
print(result)

[[ 8 14]
 [10 12]]


In [1]:
# 전치 행렬
matrix_a=[[1,2,3],[4,5,6]]

result=[[element for element in t] for t in zip(*matrix_a)]
print(result)

[[1, 4], [2, 5], [3, 6]]


In [2]:
import numpy as np

In [3]:
matrix_a=np.array([[1,2,3],[4,5,6]])
matrix_a_t=matrix_a.T
matrix_a_t2=np.transpose(matrix_a)
print(matrix_a_t)
print(matrix_a_t2)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [2]:
# 행렬의 곱
matrix_a=[[1,1,2],[2,1,1]]
matrix_b=[[1,1],[2,1],[1,3]]

In [6]:
result = [[sum(a*b for a, b in zip(row_a, column_b)) for column_b in zip(*matrix_b)] for row_a in matrix_a]
print(result)

[[5, 8], [5, 6]]


In [7]:
for row_a in matrix_a:
    print(row_a)

[1, 1, 2]
[2, 1, 1]


In [9]:
for column_b in zip(*matrix_b):
    print(column_b)

(1, 2, 1)
(1, 1, 3)


In [13]:
sum(a*b for a, b in zip(row_a, column_b))

6

In [15]:
import numpy as np

In [16]:
matrix_a=np.array([[1,1,2],[2,1,1]])
matrix_b=np.array([[1,1],[2,1],[1,3]])
result=matrix_a.dot(matrix_b)
print(result)

[[5 8]
 [5 6]]
